
dsh: 2
ns: flash.dsh2

vars:
  app_name: dsh2


init:
  - curl https://bootstrap.pypa.io/get-pip.py | python
  - pip install -U pip setuptools wheel twine keyring pypandoc tox
#  - python -c "from pypandoc.pandoc_download import download_pandoc; download_pandoc()"

test:
  - tox

install:
  - pip install -e .

package:
  - rm -rf build
  - rm -rf dist
  - pandoc -o README.rst README.md
  - python setup.py sdist bdist_wheel
  - rm README.rst

publish:
  - tox -r
  - twine upload -r pypi -u flashashen dist/{{app_name}}*
