
dsh: 2

init: 
  - pip install -U pip setuptools wheel twine keyring

test:
  - tox

install:
  - pip install -e .

package:
  - rm -rf build
  - rm -rf dist
  - python setup.py sdist bdist_wheel

publish:
  - twine upload -r pypi dist/dsh*
