
dsh: 2
ns: flash.dsh2

#vars:
#  CMDS_COMMON: &CMDS_COMMON
#    test:
#      - tox
#
#    install:
#      - pip install -e .
#
#    release:
#      - tox -r
#      - rm -rf build
#      - rm -rf dist
#      - python setup.py sdist bdist_wheel
#      - twine upload -r pypi dist/flange*


test:
  - tox

install:
  - pip install -e .

build:
  - rm -rf build
  - rm -rf dist
  - python setup.py sdist bdist_wheel
  - ls -l dist

release:
  - tox -r
  - rm -rf build
  - rm -rf dist
  - python setup.py sdist bdist_wheel
  - twine upload -r pypi dist/dsh2*
